theme: jekyll-theme-minimal
title: Cora Allen-Savietta
description: Statistics PhD Candidate with 8 years of theoretical and applied statistics experience and 2 years of software development experience. Currently developing software in Julia for efficient search & estimation in complex network space.