theme: jekyll-theme-minimal
title: Cora Allen-Coleman
description: Statistician with 6 years of theoretical and applied statistics experience and 2 years of software development experience. Currently developing software in Julia for efficient search & model comparison in complex network space.