theme: jekyll-theme-minimal
title: Dr. Cora Allen-Savietta
description: Cora builds useful statistical tools to solve real problems. Developing open-source software to uncover evolutionary mysteries at <a href="https://github.com/crsl4/PhyloNetworks.jl" target="_blank">PhyloNetworks.jl</a>