theme: jekyll-theme-minimal
title: Dr. Cora Allen-Savietta
description: Cora builds useful statistical tools to solve real problems. Designing innovative clinical trials at <a href="https://www.berryconsultants.com/" target="_blank">Berry Consultants</a>